apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/elb.id: 9e7b2a55-487d-40cc-9265-b13884b3a673
  labels:
    app: amr
  name: amr
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: amr
  sessionAffinity: None
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: amr
  name: amr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: amr
    spec:
      containers:
      - image: amrragab/swvl-project
        imagePullPolicy: Always
        name: swvl-project
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
